### ISSUE TITLE
Not working on Safari.

### ISSUE THREAD

**Issue by alexsicart** [alexsicart/Decentralized-Cloud#47]
Decentralized Cloud is not working on Safari. It should work -->[ipfs/js-ipfs#995](https://github.com/ipfs/js-ipfs/issues/995)

**Comment by alexsicart** [comment]
[ipfs/js-ipfs#995](https://github.com/ipfs/js-ipfs/issues/995)

**Comment by alexsicart** [comment]
- Build with Angular 4.
- IPFS JS 0.26
- Latest version of Safari.
- Mac OSx (latest).

**Comment by VictorBjelkholm** [comment]
Getting any errors in the console?

**Comment by sunnyday90210** [comment]
![screen shot 2017-11-06 at 10 34 06 pm](https://user-images.githubusercontent.com/26734422/32482512-e3ee12a4-c34c-11e7-8d2b-9a778b57d575.png)

**Comment by diasdavid** [comment]
I'm using the info that https://github.com/ipfs-shipyard/peerpad works 100% in Safari as a testcase for js-ipfs. What I believe it is happening in your case is that you have some dependency of a dependency that is out of that and it is not getting updated due to a .lock file.

Try: a) removing any package-lock.json or yarn.lock you have in your config, b) rm -rf node_modules, c) npm install, d) bundle it all again and see if still fails

**Comment by alexsicart** [comment]
@diasdavid @VictorBjelkholm Working, it was the package-lock.json! Thanks! 👍
